##python libraries

In [4]:
import pandas as pd

In [8]:
pd.read_csv(filepath_or_buffer="telecommunications.csv")

,Telecom__1,Telecom__2,Telecom__3,Telecom__4,Telecom__5,Telecom__6,Telecom__7,Telecom__8,Telecom__9,Telecom__10,...,Telecom__31,Telecom__32,Telecom__33,Telecom__34,Telecom__35,Telecom__36,Telecom__37,Telecom__38,Telecom__39,Telecom__40
0,9981,5279,6843,seek,approach,2429,those,material,defense,town,...,1401,country,9360,race,9374,3314,blood,put,9695,4021
1,idea,4614,763,while,relate,3625,3868,3454,organization,1790,...,2770,3175,5165,get,5790,sell,4566,5619,another,soldier
2,7151,term,948,6334,4145,less,ability,assume,8847,because,...,fact,6690,8867,5260,9486,if,7544,8048,customer,3216
3,area,1649,upon,3212,4644,market,3535,ever,west,7949,...,694,fast,7017,6683,show,brother,3632,approach,8341,684
4,6621,7584,382,1265,practice,9579,7227,standard,7580,464,...,new,8633,4145,garden,7053,1349,type,1642,personal,skin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,be,322,blood,5203,9390,find,3061,they,7481,4572,...,8419,9420,5101,2491,identify,6053,8236,8710,question,3311
9996,3094,1079,6036,everybody,upon,8658,7508,1734,4197,5940,...,8709,3092,5232,page,effect,8992,4258,4184,officer,4801
9997,784,boy,1049,3103,7398,5025,5053,finish,technology,586,...,4628,1968,1243,mind,who,course,9426,6361,4477,ok
9998,close,9124,4624,5619,2590,protect,should,benefit,6640,note,...,collection,4032,investment,section,6823,6705,first,8984,ability,3736
9999,personal,7097,1227,2114,4404,6944,certain,3693,4396,6691,...,3381,1471,6215,4426,4692,3013,like,9666,2188,9683